hospital/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers
from register.views import (
        PatientListAPIView,
        PaymentListAPIView,
        PatientRetrieveAPIView,
        PaymentRetrieveAPIView,
        )

router = routers.DefaultRouter()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('register.urls', namespace='hospital')),
    url(r'^accounts/', include('allauth.urls')),
]

urlpatterns += [
    url(r'^api/patients/$', PatientListAPIView.as_view(), name='patients_api'),
    url(r'^api/payments/$', PaymentListAPIView.as_view(), name='payments_api'),
    url(r'^api/patients/(?P<pk>\d+)/$', PatientRetrieveAPIView.as_view(), name='patients_detail_api'),
    url(r'^api/payments/(?P<pk>\d+)/$', PatientRetrieveAPIView.as_view(), name='payments_detail_api'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

register/urls.py
from django.conf.urls import url

from .views import (
    DoctorCreatelView,
    DoctorListView,
    DoctorDetailView,
    DoctorUpdatelView,
    DoctorDeleteView,
    HomePageView,
    PatientListView,
    PatientDetailView,
    PatientCreateView,
    PatientUpdatelView,
    PatientDeleteView,
    PaymentCreatelView,
    PaymentListView,
    PaymentDetailView,
    PatientDischargeDetail,
    # DischargeView,
    PatientDischargeList,
    PatientDischargeApprovedList,
    total_patients,
    payment_retrieve,
    PatientApproveView,
    PatientDischargeView,
    )


urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^discharge/$', PatientDischargeList.as_view(), name='discharge_list'),
    url(r'^discharge/approved/$', PatientDischargeApprovedList.as_view(), name='discharge_approved_list'),
    url(r'^discharge/(?P<pk>\d+)/$', PatientDischargeDetail.as_view(), name='discharge_detail'),
    # url(r'^discharge/(?P<pk>\d+)/delete/$', DischargeView.as_view(), name='discharge'),
    url(r'^discharge/(?P<pk>\d+)/approve/$', PatientApproveView.as_view(), name='discharge_approve'),
    url(r'^discharge/(?P<pk>\d+)/complete/$', PatientDischargeView.as_view(), name='discharge_complete'),


    url(r'^doctor/$', DoctorListView.as_view(), name='doctor_list'),
    url(r'^doctor/add/$', DoctorCreatelView.as_view(), name='doctor_create'),
    url(r'^doctor/(?P<pk>\d+)/$', DoctorDetailView.as_view(), name='doctor_detail'),
    url(r'^doctor/(?P<pk>\d+)/edit/$', DoctorUpdatelView.as_view(), name='doctor_update'),
    url(r'^doctor/(?P<pk>\d+)/delete/$', DoctorDeleteView.as_view(), name='doctor_delete'),

    url(r'^patient/add/$', PatientCreateView.as_view(), name='patient_create'),
    url(r'^patient/$', PatientListView.as_view(), name='patient_list'),
    url(r'^patient/(?P<pk>\d+)/$', PatientDetailView.as_view(), name='patient_detail'),
    url(r'^patient/(?P<pk>\d+)/edit/$', PatientUpdatelView.as_view(), name='patient_update'),
    url(r'^patient/(?P<pk>\d+)/delete/$', PatientDeleteView.as_view(), name='patient_delete'),

    url(r'^payment/$', PaymentListView.as_view(), name='payment_list'),
    url(r'^payment/add/$', PaymentCreatelView.as_view(), name='payment_create'),
    url(r'^payment/(?P<pk>\d+)/$', PaymentDetailView.as_view(), name='payment_detail'),
    url(r'^total/$', total_patients, name='total_patients'),
    url(r'^bills/$', payment_retrieve, name='bill_view'),

]

register/models.py
from __future__ import unicode_literals

from django.utils.translation import gettext as _
from django.db import models
from decimal import Decimal
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save, post_save
import datetime

CHOICES = (
        ('MR', 'Mr'),
        ('MRS', 'Mrs'),
        ('MISS', 'Miss'),
    )


class Doctor(models.Model):
    salutation = models.CharField(choices=CHOICES, blank=True, null=True, max_length=6)
    name = models.CharField(max_length=120, blank=True, null=True)
    degree = models.CharField(max_length=25, blank=True, null=True)
    speciality = models.CharField(max_length=120, blank=True, null=True)
    house_number = models.CharField(max_length=120, blank=True, null=True)
    street = models.CharField(max_length=120, blank=True, null=True)
    city = models.CharField(max_length=120, blank=True, null=True)
    state = models.CharField(max_length=120, blank=True, null=True)
    pin = models.PositiveIntegerField(blank=True, null=True)

    def __unicode__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('hospital:doctor_detail', kwargs={'pk': self.pk})


class Patient(models.Model):
    doctor = models.ForeignKey(Doctor, blank=True, null=True)
    salutation = models.CharField(choices=CHOICES, blank=True, null=True, max_length=6)
    name = models.CharField(max_length=120, blank=True, null=True, unique=True)
    age = models.IntegerField(blank=True, null=True)
    active = models.BooleanField(default=True)
    house_number = models.CharField(max_length=120, blank=True, null=True)
    street = models.CharField(max_length=120, blank=True, null=True)
    city = models.CharField(max_length=120, blank=True, null=True)
    state = models.CharField(max_length=120, blank=True, null=True)
    pin = models.PositiveIntegerField(blank=True, null=True)
    department = models.ForeignKey('Department', null=True)
    time_admitted = models.DateTimeField(default=datetime.datetime.now, null=True)
    time_discharged = models.DateTimeField(null=True, blank=True)
    is_approved_discharge =  models.BooleanField(default=False, verbose_name='Approve?')
    is_discharged = models.BooleanField(default=False, verbose_name='Discharge?')

    class Meta:
        ordering = ["-time_admitted"]

    def __unicode__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('hospital:patient_detail', kwargs={'pk': self.pk})

    def get_approve_url(self):
        return reverse('hospital:discharge_approve', kwargs={'pk': self.pk})

    def get_discharge_url(self):
        return reverse('hospital:discharge_complete', kwargs={'pk': self.pk})


class Payment(models.Model):
    patient = models.ForeignKey(Patient, blank=True)
    auth_by = models.ForeignKey(Doctor, related_name='payment', blank=True, null=True)
    time_billed = models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)
    medical_exp = models.DecimalField(max_digits=25, decimal_places=2, blank=True, null=True)
    rent = models.DecimalField(max_digits=25, decimal_places=2, blank=True, null=True)
    service_charges = models.DecimalField(max_digits=25, decimal_places=2, blank=True, null=True)
    subtotal = models.DecimalField(max_digits=25, decimal_places=2, default=9.99)
    tax_total = models.DecimalField(max_digits=25, decimal_places=2, default=9.99)
    total = models.DecimalField(max_digits=25, decimal_places=2,  default=9.99)
    auth_discharge = models.BooleanField(default=False)

    class Meta:
        ordering = ["-time_billed"]

    def __unicode__(self):
        return str(self.total)

    def get_absolute_url(self):
        return reverse('hospital:payment_detail', kwargs={'pk': self.pk})


def total_reciever(sender, instance, *args, **kwargs):
    medical_exp = instance.medical_exp
    rent = instance.rent
    service_charges = instance.service_charges
    subtotal = Decimal(rent)+Decimal(service_charges)+Decimal(medical_exp)
    instance.subtotal = subtotal
    tax_total = subtotal * Decimal(0.15)
    instance.tax_total = tax_total
    total = round(Decimal(subtotal) + Decimal(tax_total), 2)
    instance.total = total

pre_save.connect(total_reciever, sender=Payment)


class Department(models.Model):
    department = models.CharField(max_length=20, blank=True, null=True)
    no_of_wards = models.IntegerField(default=10)

    def __unicode__(self):
        return str(self.department)

register/forms.py
from django import forms

from .models import Doctor, Patient, Department, Payment
from decimal import Decimal
from django.db.models import Sum


class PatientAdmissionForm(forms.ModelForm):

    class Meta:
        model = Patient
        fields = ['salutation', 'name', 'doctor', 'department', 'house_number', 'street', 'city', 'state', 'pin',
                  'time_admitted',]


class PaymentForm(forms.ModelForm):

    class Meta:
        model = Payment
        fields = ['patient', 'auth_by', 'time_billed', 'medical_exp', 'rent', 'service_charges', 'auth_discharge']

register/views.py
from django.shortcuts import render, Http404, HttpResponseRedirect, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from django.core.urlresolvers import reverse_lazy, reverse
from django.views.generic.base import TemplateView
from django.contrib import messages
from django.db.models import Q
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework.authentication import SessionAuthentication
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from decimal import Decimal

from .models import Doctor, Patient, Department, Payment
from .mixins import LoginRequiredMixin, StaffRequiredMixin, DoctorRequiredMixin
from .forms import PatientAdmissionForm, PaymentForm
from .pagination import PaymentPagination, PatientPagination
from .serializers import PatientSerializer, PaymenttSerializer


class PatientListAPIView(generics.ListAPIView):
    permission_classes = [IsAuthenticatedOrReadOnly]
    queryset = Patient.objects.all()
    serializer_class = PatientSerializer
    pagination_class = PatientPagination


class PatientRetrieveAPIView(generics.RetrieveAPIView):
    permission_classes = [IsAuthenticatedOrReadOnly]
    authentication_classes = [SessionAuthentication]
    queryset = Patient.objects.all()
    serializer_class = PatientSerializer


class PaymentListAPIView(generics.ListAPIView):
    queryset = Payment.objects.all()
    serializer_class = PaymenttSerializer
    pagination_class = PaymentPagination


class PaymentRetrieveAPIView(generics.RetrieveAPIView):
    permission_classes = [IsAuthenticatedOrReadOnly]
    authentication_classes = [SessionAuthentication]
    queryset = Payment.objects.all()
    serializer_class = PaymenttSerializer


class HomePageView(TemplateView):
    template_name = "home.html"


class DoctorListView(StaffRequiredMixin, ListView):
    model = Doctor


class DoctorDetailView(StaffRequiredMixin, DetailView):
    model = Doctor
    queryset = Doctor.objects.all()


class DoctorCreatelView(StaffRequiredMixin,CreateView):
    model = Doctor
    fields = ['salutation', 'name', 'speciality', 'house_number', 'street', 'city', 'state', 'pin', ]


class DoctorUpdatelView(StaffRequiredMixin, UpdateView):
    model = Doctor
    fields = ['salutation', 'name', 'speciality', 'house_number', 'street', 'city', 'state', 'pin', ]


class DoctorDeleteView(StaffRequiredMixin, DeleteView):
    model = Doctor
    success_url = reverse_lazy('hospital:doctor_list')


class PatientListView(LoginRequiredMixin,ListView):
    model = Patient
    queryset = Patient.objects.filter(is_discharged=False)

    def get_context_data(self, **kwargs):
        context = super(PatientListView, self).get_context_data(**kwargs)
        return context


class PatientDetailView(StaffRequiredMixin, DetailView):
    model = Patient


class PatientCreateView(StaffRequiredMixin, CreateView):
    model = Patient
    fields = ['salutation', 'name', 'doctor', 'department', 'house_number', 'street', 'city', 'state', 'pin',
                  'time_admitted',]
    template_name = 'register/patient_form.html'


class PatientUpdatelView(DoctorRequiredMixin, UpdateView):
    model = Patient
    queryset = Patient.objects.filter(is_discharged=False)
    fields = ['salutation', 'name', 'doctor', 'department', 'house_number', 'street', 'city', 'state', 'pin',
                  'time_admitted', 'is_approved_discharge','is_discharged']

    def get_context_data(self, **kwargs):
        context = super(PatientUpdatelView, self).get_context_data(**kwargs)
        context['id_updated'] = self.kwargs.get('pk')
        return context


class PatientApproveView(DoctorRequiredMixin, UpdateView):
    model = Patient
    queryset = Patient.objects.filter(is_discharged=False).filter(is_approved_discharge=False)
    fields = ['salutation', 'name', 'doctor', 'department', 'time_admitted', 'is_approved_discharge']


class PatientDischargeView(DoctorRequiredMixin, UpdateView):
    queryset = Patient.objects.filter(is_approved_discharge=True)
    model = Patient
    fields = ['salutation', 'name', 'doctor', 'department', 'time_admitted', 'time_discharged', 'is_discharged']


class PatientDeleteView(StaffRequiredMixin, DeleteView):
    model = Patient
    success_url = reverse_lazy('hospital:patient_list')


class PatientDischargeApprovedList(DoctorRequiredMixin, ListView):
    model = Patient
    queryset = Patient.objects.filter(is_discharged=False).filter(is_approved_discharge=True)


class PatientDischargeList(StaffRequiredMixin, ListView):
    model = Patient
    queryset = Patient.objects.filter(is_discharged=True)


class PatientDischargeDetail(StaffRequiredMixin, DetailView):
    model = Patient
    template_name = 'register/patient_detail.html'


class PaymentCreatelView(StaffRequiredMixin,CreateView):
    model = Payment
    form_class = PaymentForm

    def get_success_url(self):
        return reverse('hospital:payment_list')


class PaymentListView(LoginRequiredMixin,ListView):
    model = Payment


def payment_retrieve(request):
    queryset_list = Payment.objects.all().order_by("-time_billed")
    if request.user.is_authenticated:
        queryset_list = Payment.objects.all()

    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
                Q(patient__name__icontains=query)|
                Q(id__icontains=query)|
                Q(time_discharged__icontains=query)
                ).distinct()
    paginator = Paginator(queryset_list, 6)
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
    "object_list": queryset,
    "page_request_var": page_request_var,

    }
    return render(request, "register/payment_list.html", context)


class PaymentDetailView(StaffRequiredMixin, DetailView):
    model = Payment
    queryset = Payment.objects.all()


class DischargeView(StaffRequiredMixin, DeleteView):
    model = Patient
    template_name = 'register/discharge_confirm.html'
    success_url = reverse_lazy('hospital:payment_list')


def total_patients(request):
    current_patients = Patient.objects.filter(is_discharged=False).count
    discharge_approved_patient = Patient.objects.filter(is_approved_discharge=True).count
    discharged_patient = Patient.objects.filter(is_discharged=True).count

    context = {
        'curr_patient': current_patients,
        'dis_patient': discharged_patient,
        # 'total_beds_available': total_beds_available,
    }
    return render(request, "register/total_patient.html", context)

templates/register/discharge_confirm.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to discharge "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

templates/register/discharge_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
<form action="" method="post">{% csrf_token %}
{{ form|crispy }}
    <input type="submit" value="Update" />
</form>
</div>
{% endblock %}

templates/register/doctor_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock content %}

templates/register/doctor_detail.html
{% extends 'base.html' %}
{% block content %}
<br/><br/>
<h4 class="sub-header">Doctor Details</h4>
          <div class="table-responsive">
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th>Sal.</th>
                  <th>Name</th>
                  <th>Speciality</th>
                  <th>House No.</th>
                  <th>Street</th>
                  <th>City</th>
                  <th>State</th>
                  <th>Delete?</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                    <td>{{ object.salutation }}</td>
                    <td>{{ object.name }}</td>
                    <td>{{ object.speciality }}</td>
                    <td>{{ object.house_number }}</td>
                    <td>{{ object.street }}</td>
                    <td>{{ object.city }}</td>
                    <td>{{ object.state }}</td>
                    <td>
                    <a href="{% url 'hospital:doctor_delete' doctor.pk %}" class="btn btn-primary">
                        <span class="glyphicon glyphicon-off" area-hidden="true"></span>
                    </a>
                    </td>
                </tr>

              </tbody>
            </table>
          </div>

{% endblock %}

templates/register/doctor_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-md-5 col-md-offset-4 main">
<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Update" />
</form>
</div>
{% endblock %}

templates/register/doctor_list.html
{% extends 'base.html' %}
{% block content %}
<br/><br/>
<div class="text-center">
<h3>Doctors List</h3>
    </div>
{% for item in object_list %}


<div class="container">
      <div class="row">
        <div class="col-lg-12">

            <a href="{{ item.get_absolute_url }}" class="btn btn-sq-lg btn-primary">
                <i class="fa fa-user fa-5x"></i>                
            </a>
             {{ item.name }} {{ item.speciality }}
        </div>
          </div>
    </div>

    <!--<table class="table table-striped">-->
    <!--<tr>-->
        <!--<td><h2>{{ item.speciality }}</h2><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></td>-->

    <!--</tr>-->
    <!--</table>-->

{% endfor %}
{% endblock %}

templates/register/patient_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock content %}

templates/register/patient_detail.html
{% extends 'base.html' %}
{% block content %}
<br/><br/>
<h2 class="sub-header">Patient Details</h2>
          <div class="table-responsive">
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th>Dept</th>
                  <th>Mr/Ms.</th>
                  <th>Name</th>
                  <th>ID</th>
                  <th>Age</th>
                  <th>Consulting Doctor</th>
                  <th>House No.</th>
                  <th>Street</th>
                  <th>City</th>
                  <th>State</th>
                  <th>Time of Admission</th>
                  <th>Update?</th>
                  <th>Delete?</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                    <td>{{ object.department.department }}</td>
                    <td>{{ object.salutation }}</td>
                    <td>{{ object.name }}</td>
                    <td>00{{ object.id }}</td>
                    <td>{{ object.age }}</td>
                    <td>{{ object.doctor }}</td>
                    <td>{{ object.house_number }}</td>
                    <td>{{ object.street }}</td>
                    <td>{{ object.city }}</td>
                    <td>{{ object.state }}</td>
                    <td>{{ object.time_admitted }}</td>
                    <td>
                        <a href="{% url 'hospital:patient_update' patient.pk %}" class="btn btn-primary">
                        <span class="glyphicon glyphicon-off" area-hidden="true"></span>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'hospital:patient_delete' patient.pk %}" class="btn btn-danger">
                        <span class="glyphicon glyphicon-off" area-hidden="true"></span>
                        </a>
                    </td>
                </tr>

              </tbody>
            </table>
          </div>

{% endblock %}

templates/register/patient_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-md-5 col-md-offset-4 main">
<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Add" />
</form>
</div>
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

</div>
{% endblock %}

templates/register/patient_list.html
{% extends 'base.html' %}
{% block content %}
<br/><br/>
<h3>Patient List</h3>
{% for item in object_list %}

    <div class="table-responsive">
        <table class="table table-striped">
            <tr>
                <td>
                    {{ forloop.counter }}) {{ item.name }}[ID NO: 00{{ item.id }}] ( Department - {{ item.department.department }})
                   <a href="{{ item.get_absolute_url }}">/Update/</a>
                     <a href="{{ item.get_approve_url }}">/Approve/</a>
                     <a href="{{ item.get_discharge_url }}">/Discharge/</a>
                   <!--<a href="{{ item.get_absolute_url }}">{{ forloop.counter }}) {{ item.name }}</a> - [ID NO: 00{{ item.id }}] ( Department - {{ item.department.department }})-->
                </td>
            </tr>
        </table>
    </div>


{% endfor %}
{% endblock %}

templates/register/payment_detail.html
{% extends 'base.html' %}
{% block content %}

<h2 class="sub-header">Bill Details</h2>
          <div class="table-responsive">
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th>Patient Name</th>
                  <th>Authorized Doctor</th>
                  <th>Admitted Time</th>
                  <th>Discharge Time</th>
                  <th>Medical Exp</th>
                  <th>Rent</th>
                  <th>Service Charges</th>
                  <th>Subtotal</th>
                  <th>Tax</th>
                  <th>Total</th>

                </tr>
              </thead>
              <tbody>
                <tr>
                    <td>{{ object.patient }}</td>
                    <td>{{ object.auth_by }}</td>
                    <td>{{ object.patient.time_admitted }}</td>
                    <td>{{ object.time_discharged }}</td>
                    <td>{{ object.medical_exp }}</td>
                    <td>{{ object.rent }}</td>
                    <td>{{ object.service_charges }}</td>
                    <td>{{ object.subtotal }}</td>
                    <td>{{ object.tax_total }}</td>
                    <td>{{ object.total }}</td>
                </tr>

              </tbody>
            </table>
          </div>

{% endblock %}

templates/register/payment_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-md-5 col-md-offset-4 main">
<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Add" />
</form>
</div>
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

</div>
{% endblock %}

templates/register/payment_list.html
{% extends 'base.html' %}
{% block content %}
<br/><br/>
<div class="text-center">
<h2>Payment List</h2>
</div>
<div class="row">
    <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
            <input type="text" class="form-control" name="q" placeholder="Search Bills" value="{{ request.GET.q }}"/>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% for item in object_list %}
    <table class="table table-striped table-responsive">
        <tr>
            <td>
               <a href="{{ item.get_absolute_url }}">{{ forloop.counter }}) BILL NO: 00{{ item.id }} - {{ item.patient }}</a>
            </td>
        </tr>
    </table>
{% endfor %}

<div class="row">
<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>
</div>

{% endblock %}

templates/register/total_patient.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block content %}
<div class="col-sm-6 col-sm-offset-4">
<div class="lead">
<!--<ol>Existing_Patients - {{ curr_patient|sub:dis_patient }}</ol>-->
<ol>Existing_Patients - {{ curr_patient }}</ol>
<ol>Total Patients Visited - {{ curr_patient|add:dis_patient }}</ol>
<ol>Total_beds_available - {{ 50|sub:curr_patient }}</ol>

</div>
</div>

{% endblock %}