hospital/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers
from register.views import (
        PatientListAPIView,
        PaymentListAPIView,
        PatientRetrieveAPIView,
        PaymentRetrieveAPIView,
        )

router = routers.DefaultRouter()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('register.urls', namespace='hospital')),
    url(r'^accounts/', include('allauth.urls')),
]

urlpatterns += [
    url(r'^api/patients/$', PatientListAPIView.as_view(), name='patients_api'),
    url(r'^api/payments/$', PaymentListAPIView.as_view(), name='payments_api'),
    url(r'^api/patients/(?P<pk>\d+)/$', PatientRetrieveAPIView.as_view(), name='patients_detail_api'),
    url(r'^api/payments/(?P<pk>\d+)/$', PatientRetrieveAPIView.as_view(), name='payments_detail_api'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

register/urls.py
from django.conf.urls import url

from .views import (
    DoctorCreatelView,
    DoctorListView,
    DoctorDetailView,
    DoctorUpdatelView,
    DoctorDeleteView,
    HomePageView,
    PatientListView,
    PatientDetailView,
    PatientCreateView,
    PatientUpdatelView,
    PatientDeleteView,
    PaymentCreatelView,
    PaymentListView,
    PaymentDetailView,
    PatientDischargeDetail,
    # DischargeView,
    PatientDischargeList,
    PatientDischargeApprovedList,
    total_patients,
    payment_retrieve,
    PatientApproveView,
    PatientDischargeView,
    )


urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^discharge/$', PatientDischargeList.as_view(), name='discharge_list'),
    url(r'^discharge/approved/$', PatientDischargeApprovedList.as_view(), name='discharge_approved_list'),
    url(r'^discharge/(?P<pk>\d+)/$', PatientDischargeDetail.as_view(), name='discharge_detail'),
    # url(r'^discharge/(?P<pk>\d+)/delete/$', DischargeView.as_view(), name='discharge'),
    url(r'^discharge/(?P<pk>\d+)/approve/$', PatientApproveView.as_view(), name='discharge_approve'),
    url(r'^discharge/(?P<pk>\d+)/complete/$', PatientDischargeView.as_view(), name='discharge_complete'),


    url(r'^doctor/$', DoctorListView.as_view(), name='doctor_list'),
    url(r'^doctor/add/$', DoctorCreatelView.as_view(), name='doctor_create'),
    url(r'^doctor/(?P<pk>\d+)/$', DoctorDetailView.as_view(), name='doctor_detail'),
    url(r'^doctor/(?P<pk>\d+)/edit/$', DoctorUpdatelView.as_view(), name='doctor_update'),
    url(r'^doctor/(?P<pk>\d+)/delete/$', DoctorDeleteView.as_view(), name='doctor_delete'),

    url(r'^patient/add/$', PatientCreateView.as_view(), name='patient_create'),
    url(r'^patient/$', PatientListView.as_view(), name='patient_list'),
    url(r'^patient/(?P<pk>\d+)/$', PatientDetailView.as_view(), name='patient_detail'),
    url(r'^patient/(?P<pk>\d+)/edit/$', PatientUpdatelView.as_view(), name='patient_update'),
    url(r'^patient/(?P<pk>\d+)/delete/$', PatientDeleteView.as_view(), name='patient_delete'),

    url(r'^payment/$', PaymentListView.as_view(), name='payment_list'),
    url(r'^payment/add/$', PaymentCreatelView.as_view(), name='payment_create'),
    url(r'^payment/(?P<pk>\d+)/$', PaymentDetailView.as_view(), name='payment_detail'),
    url(r'^total/$', total_patients, name='total_patients'),
    url(r'^bills/$', payment_retrieve, name='bill_view'),

]

templates/base.html
{% load staticfiles %}
<style>

element {

}
.col-sm-3 {

    width: 25%;

}
.col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9 {

    float: left;

}
.col-xs-6 {

    width: 50%;

}
.col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9 {

    float: left;

}
.col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9 {

    position: relative;
    min-height: 1px;
    padding-right: 15px;
    padding-left: 15px;
    padding-top: 80px;

}
</style>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>City Hospital</title>


    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="http://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">



    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    {% include 'navbar.html' %}

        <div class="container">
          <div class="row row-offcanvas row-offcanvas-right">
                    <div class="col-xs-12 col-sm-9">
                    <p class="pull-right visible-xs"></p>
                        {% block content %}{% endblock %}
                     </div>
              {% if request.user.is_authenticated %}
                      <div class="col-xs-12 col-sm-3 sidebar-offcanvas" id="sidebar">
                      <div class="list-group">
                        <a href="{% url 'hospital:home' %}" class="list-group-item active">Home</a>
                        <a href="{% url 'hospital:doctor_list' %}" class="list-group-item">Doctors</a>
                        <a href="{% url 'hospital:patient_list' %}" class="list-group-item">Current Patients</a>
                        <a href="{% url 'hospital:payment_create' %}" class="list-group-item">Create Invoice</a>
                        <a href="{% url 'hospital:patient_create' %}" class="list-group-item">New Patient</a>
                        <a href="{% url 'hospital:payment_list' %}" class="list-group-item">Existing Bills</a>
                        <a href="{% url 'hospital:discharge_approved_list' %}" class="list-group-item">Patient Approved for Discharge</a>
                        <a href="{% url 'hospital:discharge_list' %}" class="list-group-item">Discharge List</a>
                        <a href="{% url 'hospital:total_patients' %}" class="list-group-item">Patient Data</a>
                        <a href="{% url 'hospital:bill_view' %}" class="list-group-item">Bill Data</a>
                        <a href="{% url 'patients_api' %}" class="list-group-item">DRF Patients</a>
                        <a href="{% url 'payments_api' %}" class="list-group-item">DRF Payments</a>
                      </div>
                    </div><!--/.sidebar-offcanvas-->
             </div><!--/.col-xs-12.col-sm-9-->
    {% endif %}


    </div><!--/.container-->
       <hr/>
    <div class="container">
        <footer>
        <p>&copy; 2015 Company, Inc.</p>
      </footer>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
 <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="http://getbootstrap.com/assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/base_old.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>My Hospital</title>
    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="http://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
       <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">City Hospital</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            {% if not login %}
            <li><a href="{% url 'account_login' %}">Login</a></li>{% endif %}
            <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
            <li><a href="{% url 'account_logout' %}">Logout</a></li>
            <li><a href="#">Help</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
            <li><a href="{% url 'hospital:home' %}">Home</a></li>
            <li><a href="{% url 'hospital:doctor_list' %}">Doctors</a></li>
            <li><a href="{% url 'hospital:patient_create' %}">New Patient</a></li>
            <li><a href="{% url 'hospital:patient_list' %}">Current Patients</a></li>
            <li><a href="{% url 'hospital:payment_create' %}">Create Invoice</a></li>
            <li><a href="{% url 'hospital:payment_list' %}">Existing Bills</a></li>
            <li><a href="{% url 'hospital:discharge_approved_list' %}">Patient Approved for Discharge</a></li>
            <li><a href="{% url 'hospital:discharge_list' %}">Discharge List</a></li>
            <li><a href="{% url 'hospital:total_patients' %}">Patient Data</a></li>
          </ul>
        </div>
        <div class="col-sm-4 col-sm-offset-2">
          <br/><br/><br/><br/>
          <img src="http://webneel.com/image/logo/22-pharmacy-logo-idea.gif" width="500" height="500" class="img-responsive">
        </div>
      </div>
    </div>
    <div>
    {% block content %}{% endblock %}
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="http://getbootstrap.com/assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/home.html
{% load staticfiles %}
<style>

element {

}
.col-sm-3 {

    width: 25%;

}
.col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9 {

    float: left;

}
.col-xs-6 {

    width: 50%;

}
.col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9 {

    float: left;

}
.col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9 {

    position: relative;
    min-height: 1px;
    padding-right: 15px;
    padding-left: 15px;
    padding-top: 80px;

}
</style>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>City Hospital</title>
    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="http://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
  {% include 'navbar.html' %}
<!--<div class="navbar-wrapper">-->
    <!--<div class="container-fluid">-->
        <!--<nav class="navbar navbar-fixed-top">-->
            <!--<div class="container">-->
                <!--<div class="navbar-header">-->
                    <!--<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">-->
                    <!--<span class="sr-only">Toggle navigation</span>-->
                    <!--<span class="icon-bar"></span>-->
                    <!--<span class="icon-bar"></span>-->
                    <!--<span class="icon-bar"></span>-->
                    <!--</button>-->
                    <!--<a class="navbar-brand" href="#">Logo</a>-->
                <!--</div>-->
                <!--<div id="navbar" class="navbar-collapse collapse">-->
                    <!--<ul class="nav navbar-nav">-->
                        <!--<li class="active"><a href="#" class="">Home</a></li>-->
                        <!--<li class=" dropdown">-->
                            <!--<a href="#" class="dropdown-toggle " data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Departments <span class="caret"></span></a>-->
                            <!--<ul class="dropdown-menu">-->
                                <!--<li class=" dropdown">-->
                                    <!--<a href="#" class="dropdown-toggle " data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">View Departments</a>-->
                                <!--</li>-->
                                <!--<li><a href="#">Add New</a></li>-->
                            <!--</ul>-->
                        <!--</li>-->
                        <!--<li><a href="#">Add New</a></li>-->
                        <!--<li class=" dropdown"><a href="#" class="dropdown-toggle " data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Managers <span class="caret"></span></a>-->
                            <!--<ul class="dropdown-menu">-->
                                <!--<li><a href="#">View Managers</a></li>-->
                                <!--<li><a href="#">Add New</a></li>-->
                            <!--</ul>-->
                        <!--</li>-->
                        <!--<li class=" dropdown"><a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Staff <span class="caret"></span></a>-->
                            <!--<ul class="dropdown-menu">-->
                                <!--<li><a href="#">View Staff</a></li>-->
                                <!--<li><a href="#">Add New</a></li>-->
                                <!--<li><a href="#">Bulk Upload</a></li>-->
                            <!--</ul>-->
                        <!--</li>-->
                        <!--<li class=" down"><a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">HR <span class="caret"></span></a>-->
                            <!--<ul class="dropdown-menu">-->
                                <!--<li><a href="#">Change Time Entry</a></li>-->
                                <!--<li><a href="#">Report</a></li>-->
                            <!--</ul>-->
                        <!--</li>-->
                    <!--</ul>-->
                    <!--<ul class="nav navbar-nav pull-right">-->
                        <!--<li class=" dropdown"><a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Signed in as  <span class="caret"></span></a>-->
                            <!--<ul class="dropdown-menu">-->
                                <!--<li><a href="#">Change Password</a></li>-->
                                <!--<li><a href="#">My Profile</a></li>-->
                            <!--</ul>-->
                        <!--</li>-->
                        <!--<li class=""><a href="#">Logout</a></li>-->
                    <!--</ul>-->
                <!--</div>-->
            <!--</div>-->
        <!--</nav>-->
    <!--</div>-->
<!--</div>-->


    <div class="container">
      <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
          <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="http://www.kevincottam.com/wp-content/uploads/2014/08/Mahatma-Gandhi.png" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>City Hospital</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="http://www.kevincottam.com/wp-content/uploads/2014/08/Mahatma-Gandhi.png" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>City Hospital</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="http://www.kevincottam.com/wp-content/uploads/2014/08/Mahatma-Gandhi.png" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>City Hospital</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="http://www.kevincottam.com/wp-content/uploads/2014/08/Mahatma-Gandhi.png" alt="Generic placeholder thumbnail">
              <h4>City Hospital</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>






          <!--<div class="row">-->
             <!--<div class="col-xs-12 col-sm-7">-->
            <!--<form class="form-signin" action="{% url 'account_login' %}">-->
              <!--<h2 class="form-signin-heading">Please sign in</h2>-->
              <!--<label for="inputUsername" class="sr-only">Username</label>-->
              <!--<input type="username" id="inputUsername" class="form-control" placeholder="Username" required autofocus>-->
              <!--<label for="inputPassword" class="sr-only">Password</label>-->
              <!--<input type="password" id="inputPassword" class="form-control" placeholder="Password" required>-->
              <!--<div class="checkbox">-->
                <!--<label>-->
                  <!--<input type="checkbox" value="remember-me"> Remember me-->
                <!--</label>-->
              <!--</div>-->
              <!--<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>-->
            <!--</form>-->
           <!--</div>-->
          <!--</div>&lt;!&ndash;/row&ndash;&gt;-->
        </div><!--/.col-xs-12.col-sm-9-->





        <div class="col-xs-12 col-sm-3 sidebar-offcanvas" id="sidebar">
                  <div class="list-group">
                    <a href="{% url 'hospital:home' %}" class="list-group-item active"> Home</a>
                    <a href="{% url 'hospital:doctor_list' %}" class="list-group-item">Doctors</a>
                    <a href="{% url 'hospital:patient_list' %}" class="list-group-item">Current Patients</a>
                    <a href="{% url 'hospital:payment_create' %}" class="list-group-item">Create Invoice</a>
                    <a href="{% url 'hospital:patient_create' %}" class="list-group-item">New Patient</a>
                    <a href="{% url 'hospital:payment_list' %}" class="list-group-item">Existing Bills</a>
                    <a href="{% url 'hospital:discharge_approved_list' %}" class="list-group-item">Patient Approved for Discharge</a>
                    <a href="{% url 'hospital:discharge_list' %}" class="list-group-item">Discharge List</a>
                    <a href="{% url 'hospital:total_patients' %}" class="list-group-item">Patient Data</a>
                    <a href="{% url 'hospital:bill_view' %}" class="list-group-item">Bill Data</a>
                    <a href="{% url 'patients_api' %}" class="list-group-item">DRF Patients</a>
                    <a href="{% url 'payments_api' %}" class="list-group-item">DRF Payments</a>
                  </div>
                </div><!--/.sidebar-offcanvas-->
      </div><!--/row-->
      <hr>

    </div><!--/.container-->

    <div class="container">
        <footer>
        <p>&copy; 2015 Company, Inc.</p>
      </footer>
    </div>




    <!-- Bootstrap core JavaScript
    ================================================== -->
 <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="http://getbootstrap.com/assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">City Hospital</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
              {% if request.user.is_authenticated %}
            <li><a href="{% url 'account_logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'account_login' %}">Login</a></li>
            <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
            {% endif %}
            <li><a href="#">Help</a></li>
          </ul>

        </div>
      </div>
    </nav>